### PR TITLE
alternative preload

### PR DESCRIPTION
**Pull request by VanillaMaster**
> status: WIP

Currently preloading starts too early, no document exists yet, and using `DOMContentLoaded` to delay execution of preload script also dont gonna work, cuz when event get fiered its too late, general script execution already `done`/`pending`.
The perfect moment ot execute preload script is at [`document_start`](https://developer.chrome.com/docs/extensions/reference/api/extensionTypes#type-RunAt), so injecting script tag directly into the page (just before main scripts) is not the worst idea

this change could allow me to start working on node modules compatibility

### CODE REVIEW

**Comment by BakaFT** [comment]
I don't see any substantial benefits from this commit.

> Currently preloading starts too early, no document exists yet

What‘s the benefit of delaying it? Or rather, what are the drawbacks of executing it too early? You chose to use a resource request handler to intercept, compare, and possibly process every request in the browser. This might cause some performance loss.

If the preload script worked perfectly before the modification and still works perfectly after it. Then what's the point of this commit? Is it just to increase performance overhead or for fun?

Interceptors can be a good solution for certain issues, and I see you seem to have ideas about intercepting and modifying other responses as well. However, this should not be done in the Core. It should be done as an optionally enabled Native Extension.

> this change could allow me to start working on node modules compatibility

 Why? Can you provide additional explanations for this?

**Comment by VanillaMaster** [comment]
> this change could allow me to start working on node modules compatibility

I want to allow plugins to use npm packages as is without bundling with all its dependencies (and allow every plugin just be just npm package)
the perfect scenario is allow user symlink `plugins` folder into `node_modules` and use npm/yarn/pnpm/etc to manage installed plugins

To achive this I need to mimic node resolution behaviour in whatwg host environment, there is 2 general approaches 1) to transpile code on flight 2) make use of importmap. First one is generally slow, so I want to avoid it, second one requires injecting importmap before module script evaluation, and it's not possible to do it reliably in current implementation.

The changes I've done allows to mess with main page in whatever way I want, at cost of slightly bigger overhead

**Comment by nomi-san** [comment]
I always say no to filter/intercept HTTP req/responses. The new loader is built on top of Tauri (webview2/webkit) will allow you to transpile the (TS) plugins on the fly when installing. `node_modules` is terrible, will a normal LoL gamer allow to install npm and Pengu folder with 100MB of code?

**Comment by BakaFT** [comment]
>the perfect scenario is allow user symlink plugins folder into node_modules and use npm/yarn/pnpm/etc to manage installed plugins

You are assuming all users are devs when some users don't even know how to install a plugin correctly.

And set aside the Node compatibility issues you mentioned. Introducing many new stuffs and either reducing performance or 
 altering the code structure just to provide a new implementation for an already complete feature is ridiculous.

**Comment by VanillaMaster** [comment]
> node_modules is terrible, will a normal LoL gamer allow to install npm and Pengu folder with 100MB of code?

if its optional i dont see any problems (if be real how much different `node_modules` folder with packages and and currently used `plugins` folder, arent they identical ?)

> You are assuming all users are devs when some users don't even know how to install a plugin correctly.

not realy, currently i must just dump plugin into folder, and cant use npm for managing them, cuz loader doesnt know anything about package.json. Allowing usage of package manager would not restrict user from dumping plugin into folder, just like now

>And set aside the Node compatibility issues you mentioned. Introducing many new stuffs and either reducing performance or altering the code structure just to provide a new implementation for an already complete feature is ridiculous.

yes ... i guess

**Pull request closed without merging**
